# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/java-tron
    steps:
    - add_ssh_keys:
        fingerprints:
          - "w3l8nzwJI0JHSITUocGV/RE6sXWssMlJVS9tV9MwrY8"
    - checkout
    - run: cp -f config/checkstyle/checkStyle.xml config/checkstyle/checkStyleAll.xml
    - run: ./gradlew build -x test
    - run: sudo bash deploy.sh

#  test:
#    docker:
#    - image: circleci/openjdk:8-jdk-browsers
#    steps:
#    - run: sudo bash deploy.sh

