# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/java-tron
    steps:
    - checkout
    - run: ./gradlew build

  test:
    steps:
    - run: sudo bash deploy.sh

